/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuView.java
 *
 * Created on Sep 22, 2013, 11:59:31 PM
 */

package com.pks.gms.ui;

import org.jdesktop.application.Action;

/**
 *
 * @author VAIO
 */
public class MenuView extends javax.swing.JFrame {

    /** Creates new form MenuView */
    public MenuView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewTranButton = new javax.swing.JButton();
        entryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.pks.gms.GmsApp.class).getContext().getResourceMap(MenuView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.pks.gms.GmsApp.class).getContext().getActionMap(MenuView.class, this);
        viewTranButton.setAction(actionMap.get("listTransaction")); // NOI18N
        viewTranButton.setText(resourceMap.getString("viewTranButton.text")); // NOI18N
        viewTranButton.setName("viewTranButton"); // NOI18N

        entryButton.setAction(actionMap.get("transactionEntry")); // NOI18N
        entryButton.setText(resourceMap.getString("entryButton.text")); // NOI18N
        entryButton.setName("entryButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entryButton)
                    .addComponent(viewTranButton))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(entryButton)
                .addGap(18, 18, 18)
                .addComponent(viewTranButton)
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    @Action
    public void transactionEntry(){
        new TransactionEntryView().setVisible(true);
    }
    @Action
    public void listTransaction(){
        new ListTransaction().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entryButton;
    private javax.swing.JButton viewTranButton;
    // End of variables declaration//GEN-END:variables

}
