// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pks.inm.domain;

import com.pks.inm.domain.Incident;
import com.pks.inm.domain.IncidentDataOnDemand;
import com.pks.inm.domain.IncidentIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect IncidentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IncidentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IncidentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: IncidentIntegrationTest: @Transactional;
    
    @Autowired
    IncidentDataOnDemand IncidentIntegrationTest.dod;
    
    @Test
    public void IncidentIntegrationTest.testCountIncidents() {
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", dod.getRandomIncident());
        long count = Incident.countIncidents();
        Assert.assertTrue("Counter for 'Incident' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IncidentIntegrationTest.testFindIncident() {
        Incident obj = dod.getRandomIncident();
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Incident' failed to provide an identifier", id);
        obj = Incident.findIncident(id);
        Assert.assertNotNull("Find method for 'Incident' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Incident' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IncidentIntegrationTest.testFindAllIncidents() {
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", dod.getRandomIncident());
        long count = Incident.countIncidents();
        Assert.assertTrue("Too expensive to perform a find all test for 'Incident', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Incident> result = Incident.findAllIncidents();
        Assert.assertNotNull("Find all method for 'Incident' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Incident' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IncidentIntegrationTest.testFindIncidentEntries() {
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", dod.getRandomIncident());
        long count = Incident.countIncidents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Incident> result = Incident.findIncidentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Incident' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Incident' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IncidentIntegrationTest.testFlush() {
        Incident obj = dod.getRandomIncident();
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Incident' failed to provide an identifier", id);
        obj = Incident.findIncident(id);
        Assert.assertNotNull("Find method for 'Incident' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIncident(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Incident' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IncidentIntegrationTest.testMergeUpdate() {
        Incident obj = dod.getRandomIncident();
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Incident' failed to provide an identifier", id);
        obj = Incident.findIncident(id);
        boolean modified =  dod.modifyIncident(obj);
        Integer currentVersion = obj.getVersion();
        Incident merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Incident' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IncidentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", dod.getRandomIncident());
        Incident obj = dod.getNewTransientIncident(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Incident' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Incident' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Incident' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void IncidentIntegrationTest.testRemove() {
        Incident obj = dod.getRandomIncident();
        Assert.assertNotNull("Data on demand for 'Incident' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Incident' failed to provide an identifier", id);
        obj = Incident.findIncident(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Incident' with identifier '" + id + "'", Incident.findIncident(id));
    }
    
}
