// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pks.inm.domain;

import com.pks.inm.domain.Status;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Status_Roo_Configurable {
    
    declare @type: Status: @Configurable;
    
}
