// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pks.inm.domain;

import com.pks.inm.domain.Status;

privileged aspect Status_Roo_JavaBean {
    
    public String Status.getStatus() {
        return this.status;
    }
    
    public void Status.setStatus(String status) {
        this.status = status;
    }
    
}
