// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pks.jtest.domain;

import com.pks.jtest.domain.Product;

privileged aspect Product_Roo_JavaBean {
    
    public String Product.getProductName() {
        return this.productName;
    }
    
    public void Product.setProductName(String productName) {
        this.productName = productName;
    }
    
}
